version: '3.8'

services:
  lock-manager:
    image: sudeep162002/lock-manager:latest
    container_name: lock-manager
    ports:
      - "3000:3000"
    networks:
      - locks-network

  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - locks-network

networks:
  locks-network:
    driver: bridge
