version: '3.8'

services:
  clojure-locks:
    image: clojure
    container_name: clojure-locks
    ports:
      - "3000:3000"
    volumes:
      - /D/web_development:/src
    working_dir: /src
    tty: true
    stdin_open: true
    depends_on:
      - redis
    networks:
      - locks-net

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - locks-net

networks:
  locks-net:
    driver: bridge
